package com.ecommerce.common.dto.request;

import com.fasterxml.jackson.annotation.JsonFormat;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class RequestEnvelope<T> {

    /**
     * Unique identifier for this request.
     * Generated by client OR injected by API Gateway if missing.
     * Propagated via X-Request-Id header to ALL downstream services.
     * Used for: logging, audit trail, distributed tracing, support debugging.
     */
    private String requestId;

    /**
     * ID of the authenticated user making the request.
     * Populated by API Gateway after JWT validation.
     * Optional - null for unauthenticated endpoints (login, register).
     */
    private String userId;

    /**
     * The actual request-specific data.
     * @Valid triggers cascaded bean validation on the payload object.
     */
    @NotNull(message = "Request payload must not be null")
    @Valid
    private T payload;

    /**
     * Client-side timestamp of when the request was created.
     * Server uses this to detect very stale requests (optional enforcement).
     */
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    @Builder.Default
    private LocalDateTime timestamp = LocalDateTime.now();
}
